### ISSUE TITLE
single-sample details not displayed correctly

### ISSUE THREAD

**Issue by kwkroll32** [tahatopiwala/QuaCRS#4]
I clicked on the sample ID on the front page and did not see anything at all. The popup appears, but it is blank. I haven't seen any errors about it so don't quite know where to begin troubleshooting. 
![issue4](https://cloud.githubusercontent.com/assets/8041208/11666457/930f5c8a-9dba-11e5-9d19-1ad262e8e948.PNG)

**Comment by tahatopiwala** [comment]
You will have to make the same changes you made on line 157 changing it to General. So that specific method specifies which tables should be avoided. So the names of the tables must match all the database tables that you have. According to what I have all the tables are lower case making it easy to add them to the query.

**Comment by kwkroll32** [comment]
That doesn't seem to be the issue. I renamed the table in my database from "General" to "general" to match yours, but the same problem persists. Also, I undid my capitalization of "general" that I had made earlier, in the sample model.

**Comment by tahatopiwala** [comment]
Okay. This seems to mostly be a cross origin issue that is persisting. It doesn't make sense as to why there would be an issue as such that because it works well on the compare page. I would suggest clicking on the sample on the main page and then going to the browser inspector menu to inspect the web page. You might see incase it there is an error in the console.

**Comment by kwkroll32** [comment]
"Failed to load resource: the server responded with a status of 404 (Not Found): http://bioserv.mps.ohio-state.edu/QuaCRS/index.php/sample/singleView "

Make sense?

**Comment by tahatopiwala** [comment]
Yes. It is because you have added the new code to a folder named QuaCRS2. You must change the link in the javascript file named drag2.0.js in assets/js

**Comment by kwkroll32** [comment]
That worked. Is there a way to make drag2.0.js more robust so it doesn't care about the name? If it's easier, the path will be specified by the user in application/config/config.php. Can you pull the name from there? There's no guarantee that it'll be QuaCRS, as you can see.

**Comment by tahatopiwala** [comment]
Yes that should be possible. I will have to add some code to and I will commit the changes to the master branch. To get the latest working code just pull from the master branch and not the changes branch. I have added the feature to save the compare results and I have made changes to the a couple of file and all the changes have been pushed and committed to the changes branch and not the master

**Comment by kwkroll32** [comment]
Unrelated to this issue but in light of your issue closing/reopening spam, feel free to close any of these AFTER you push the fix to master. You can do so manually after pushing, or automatically using some keywords: https://help.github.com/articles/closing-issues-via-commit-messages/
